openapi: 3.1.0
info:
  title: FantasyPros MLB Lineups
  description: Retrieves today's projected and confirmed MLB lineups from FantasyPros.
  version: 1.0.0
servers:
  - url: https://www.fantasypros.com
    description: FantasyPros server
paths:
  /mlb/lineups/json.php:
    get:
      operationId: getFantasyProsLineups
      summary: Get today's MLB lineups from FantasyPros
      description: Returns all MLB lineups for today, including confirmation status and batting order.
      responses:
        '200':
          description: Lineups returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    team:
                      type: string
                      description: 3-letter abbreviation
                    team_name:
                      type: string
                    confirmed:
                      type: boolean
                      description: True if the lineup is confirmed by the team
                    players:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          batting_order:
                            type: integer
                          position:
                            type: string
