openapi: 3.1.0
info:
  title: MLB Lineup Audit API
  version: 1.0.0
  description: |
    Pulls full lineup audit data for a given MLB game date using live metrics (Statcast, Fangraphs, Vegas, and weather).

servers:
  - url: https://mlbrbis-1.onrender.com/api/v1
    description: Production server on Render

paths:
  /audit/{target}:
    get:
      operationId: auditLineupsByDate
      summary: Run a full audit for lineups on a given date
      parameters:
        - name: target
          in: path
          required: true
          description: |
            Use `"today"`, `"yesterday"`, or a specific date in the format `YYYY-MM-DD`.
          schema:
            type: string
            example: "2024-07-01"
      responses:
        '200':
          description: Audit results per player
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    team:
                      type: string
                    mlbamId:
                      type: integer
                    slot:
                      type: integer
                    audit:
                      type: object
                      properties:
                        powerSignal:
                          type: object
                        volumeOpportunity:
                          type: object
                        opponentWeakness:
                          type: object
                        runEnvironment:
                          type: object
                        recentForm:
                          type: object
                        pitchEdge:
                          type: object
