openapi: 3.1.0
info:
  title: RBI Audit Backend
  version: 1.2.0
  description: |
    GPT-connected backend for fully automated 2025 MLB RBI audit. Includes player-level endpoints
    and batch audit of all confirmed hitters in today's lineups.
servers:
  - url: https://mlbrbis-1.onrender.com/api/v1
    description: Render backend
paths:
  /audit/today:
    get:
      operationId: auditAllTodayHitters
      summary: Run a full RBI audit for all confirmed hitters in today's lineups.
      responses:
        '200':
          description: RBI audit results
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    team:
                      type: string
                    mlbamId:
                      type: string
                    slot:
                      type: integer
                    audit:
                      type: object
  /lineup-slot:
    get:
      operationId: getLineupSlot
      summary: Get confirmed lineup slot.
      parameters:
        - name: mlbamId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Confirmed lineup slot
          content:
            application/json:
              schema:
                type: object
                properties:
                  slot:
                    type: string
  # ... you can add your other endpoints here (see earlier messages)
