openapi: 3.1.0
info:
  title: MLB Manual Lineup Audit API
  version: 1.0.0
  description: |
    Submit plaintext MLB lineups to get a full player-by-player audit using live data.

servers:
  - url: https://mlbrbis-1.onrender.com/api/v1
    description: Production server

paths:
  /audit/parse:
    post:
      operationId: auditFromPlainText
      summary: Run a full audit from a manually entered lineup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  example: |
                    Los Angeles Dodgers Lineup
                    1 Mookie Betts (2B)
                    2 Freddie Freeman (1B)
                    3 Shohei Ohtani (DH)
      responses:
        '200':
          description: Audit results per player
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    team:
                      type: string
                    mlbamId:
                      type: integer
                    slot:
                      type: integer
                    confirmed:
                      type: boolean
                    audit:
                      type: object
                      properties:
                        powerSignal:
                          type: object
                        volumeOpportunity:
                          type: object
                        opponentWeakness:
                          type: object
                        runEnvironment:
                          type: object
                        recentForm:
                          type: object
                        pitchEdge:
                          type: object
