openapi: 3.1.0
info:
  title: MLB Lineups Tool
  description: Retrieve confirmed MLB lineups from the official MLB Stats API.
  version: 1.0.0
servers:
  - url: https://your-deployment.com
    description: Your deployed backend that calls statsapi.mlb.com
paths:
  /lineups:
    get:
      operationId: getMlbLineups
      summary: Get confirmed MLB lineups for a date
      description: Returns confirmed starting lineups for all MLB games on a given date.
      parameters:
        - name: date
          in: query
          required: true
          schema:
            type: string
            format: date
            example: 2024-09-01
      responses:
        '200':
          description: Confirmed lineups returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    game:
                      type: string
                    homeTeam:
                      type: string
                    awayTeam:
                      type: string
                    homeLineup:
                      type: array
                      items:
                        type: object
                        properties:
                          fullName:
                            type: string
                          position:
                            type: string
                          battingOrder:
                            type: string
                    awayLineup:
                      type: array
                      items:
                        type: object
                        properties:
                          fullName:
                            type: string
                          position:
                            type: string
                          battingOrder:
                            type: string
