openapi: 3.1.0
info:
  title: MLB Lineup Audit API
  version: 1.0.0
  description: |
    Provides a full player-by-player lineup audit using live MLB data:
    - Lineups from RotoWire
    - Weather from MLB.com
    - Statcast, Fangraphs, Vegas odds, etc.

servers:
  - url: https://mlbrbis-1.onrender.com/api/v1
    description: Production server

paths:
  /audit/today:
    get:
      operationId: auditTodayLineups
      summary: Run a full audit for today’s confirmed lineups
      responses:
        '200':
          description: Player audit results
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    team:
                      type: string
                    mlbamId:
                      type: integer
                    slot:
                      type: integer
                    audit:
                      type: object
                      properties:
                        powerSignal:
                          type: object
                        volumeOpportunity:
                          type: object
                        opponentWeakness:
                          type: object
                        runEnvironment:
                          type: object
                        recentForm:
                          type: object
                        pitchEdge:
                          type: object
