openapi: 3.1.0
info:
  title: MLB Manual Lineup Audit API
  version: 1.0.0
  description: |
    Submit raw plaintext MLB lineups and receive full player-by-player audits with live stats.

servers:
  - url: https://mlbrbis-1.onrender.com/api/v1

paths:
  /audit/parse:
    post:
      operationId: auditFromText
      summary: Run a full audit from manually entered lineup text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - text
              properties:
                text:
                  type: string
                  example: |
                    Los Angeles Dodgers Lineup
                    1 Mookie Betts
                    2 Freddie Freeman
                    3 Shohei Ohtani
      responses:
        '200':
          description: Full audit results
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
