openapi: 3.1.0
info:
  title: MLB Lineups Tool
  description: Get confirmed MLB lineups for a given date.
  version: 1.0.0
servers:
  - url: https://your-app.onrender.com
    description: Your deployed server
paths:
  /lineups:
    get:
      operationId: getMlbLineups
      summary: Get MLB lineups for a specific date
      parameters:
        - name: date
          in: query
          required: true
          description: Date of the MLB games in YYYY-MM-DD format
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Confirmed lineups with players and batting order
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    game:
                      type: string
                    homeTeam:
                      type: string
                    awayTeam:
                      type: string
                    homeLineup:
                      type: array
                      items:
                        type: object
                        properties:
                          fullName:
                            type: string
                          position:
                            type: string
                          battingOrder:
                            type: string
                    awayLineup:
                      type: array
                      items:
                        type: object
                        properties:
                          fullName:
                            type: string
                          position:
                            type: string
                          battingOrder:
                            type: string
